name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/publish-common.yml
    with:
      files: zehnder-comfoair-q-esp32-evb.yml,zehnder-comfoair-q-m5stack-atom.yml,zehnder-comfoair-q-m5stack-atoms3.yml
      name: Zehnder ComfoAir Q
